backend:
  name: git-gateway

media_folder: "static/assets/img/games"
public_folder: "/assets/img/games"

collections:
  - name: "_platforms"
    label: "Platforms"
    label_singular: "Platform"
    folder: "content/_platform"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Company", name: "company", widget: "string"}
      - {label: "Logo", name: "logo", widget: "text"}
      - {label: "Disc", name: "disc", widget: "boolean"}
      - {label: "Cartridge", name: "cartridge", widget: "boolean"}
      - {label: "Color", name: "color", required: false, widget: "string"}
      - {label: "Order", name: "order", required: false, widget: "number"}
  - name: "_genres"
    label: "Genres"
    label_singular: "Genre"
    folder: "content/_genre"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Icon", name: "icon", widget: "string"}
  - name: "games"
    label: "Games"
    label_singular: "Game"
    folder: "content/games"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Note", name: "note", required: false, widget: "string"}
      - {label: "Platform", name: "platform", widget: "relation", collection: "_platforms", value_field: "slug", display_fields: ["title"], search_fields: ["title"]}
      - {label: "Genre", name: "genre", widget: "relation", collection: "_genres", value_field: "slug", display_fields: ["title"], search_fields: ["title"], multiple: true}
      - {label: "Physical", name: "physical", required: false, widget: "boolean"}
      - {label: "Digital", name: "digital", required: false, widget: "boolean"}
      - {label: "Guide", name: "guide", required: false, widget: "boolean"}
      - {label: "Pending", name: "pending", required: false, widget: "boolean"}
      - {label: "Posted", name: "posted", widget: "date", default: "YYYY-MM-DD", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD"}
  - name: "systems"
    label: "Systems"
    label_singular: "System"
    folder: "content/systems"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Platform", name: "platform", widget: "relation", collection: "_platforms", value_field: "slug", display_fields: ["title"], search_fields: ["title"]}
      - {label: "System Type", name: "system_type", widget: "select", options: [{label: "Console", value: "console"}, {label: "Handheld", value: "handheld"}, {label: "Hybrid", value: "hybrid"}, {label: "Mini", value: "mini"}]}
      - {label: "Variation", name: "variation", required: false, widget: "string"}
  - name: "controllers"
    label: "Controllers"
    label_singular: "Controller"
    folder: "content/controllers"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Variation", name: "variation", required: false, widget: "list"}
      - {label: "Connection", name: "connection", required: false, widget: "list"}
      - {label: "Company", name: "company", widget: "relation", collection: "_controllers-company", value_field: "slug", display_fields: ["title"], search_fields: ["title"]}
  - name: "_controllers-company"
    label: "Company"
    label_singular: "Company"
    folder: "content/_controllers-company"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Logo", name: "logo", widget: "text"}